### ISSUE TITLE
ModuleNotFoundError: No module named 'tsr'

### ISSUE THREAD

**Issue by mesmol** [KVignesh122/image-to-3D#1]
Hi, and thanks for the hard work.
When I run the converter file I get the ModuleNotFoundError: No module named 'tsr' error.
I installed the tsr package using pip on my system, but the error persists. I'm not sure how to move forward.

**Comment by reaperhammer** [comment]
Same... also more:

2024-10-13 18:30:40.3894620 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:2103 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
2024-10-13 18:31:41,715 - INFO - Initializing model ...
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1967, in __call__
  File "ui.py", line 49, in process_image
  File "run.py", line 48, in convert_to_3d
    model = TSR.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^
  File "system.py", line 57, in from_pretrained
    model = cls(cfg)
            ^^^^^^^^
  File "utils.py", line 58, in __init__
    self.configure(*args, **kwargs)
  File "system.py", line 63, in configure
    self.image_tokenizer = find_class(self.cfg.image_tokenizer_cls)(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 27, in find_class
    module = importlib.import_module(module_string, package=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tsr'

**Comment by reaperhammer** [comment]
Further to that, I have a few questions;
Why does the project not contain all the dependencies or instruction how to build from source? Your build has things not in the project.
Can I suggest you add a commandline switch functionality so we don't need to run an exe at all?

**Comment by KVignesh122** [comment]
Did you guys do step 2 of downloading the relevant files (model.ckpt and config.yaml ) from HuggingFace?
https://huggingface.co/stabilityai/TripoSR/tree/main
